#
# DragonFly pkg mirrorselect
#

# Uncomment to turn on debug
debug = true

listen = "127.0.0.1:3130"

# Uncomment to write log to a file
#log_file = "mirrorselect.log"

# File containing the mirrors (path relative to this file)
mirror_list = "mirrors.dev.toml"

# MaxMind GeoLite2 database file
mmdb_file = "GeoLite2-City_20201006.mmdb"

# Settings for mirror monitor
#
[monitor]
# Interval in seconds between monitor rounds
interval = 60
# Timeout set for requesting mirrors
timeout = 5
# Number of consecutive opposite status before flipping mirror's status
hysteresis = 3
# Whether to verify the server's certificate?
tls_verify = false
