#
# DragonFly pkg mirrorselect
#

# Uncomment to turn on debug
debug = true

listen = "127.0.0.1:3130"

# Uncomment to write log to a file
#logfile = "mirrorselect.log"

# File containing the mirrors (path relative to this file)
mirrorlist = "mirrors.toml"

# MaxMind GeoLite2 database file
mmdbfile = "GeoLite2-City_20201006.mmdb"
