#
# DragonFly pkg mirrorselect
#

# Uncomment to turn on debug
debug = true

listen = "127.0.0.1:3130"

# Uncomment to write log to a file
#log_file = "mirrorselect.log"

# File containing the mirrors (path relative to this file)
mirror_list = "mirrors.dev.toml"

# MaxMind GeoLite2 database file
mmdb_file = "GeoLite2-City_20201006.mmdb"
